# admin/config.yml

# Backend configuratie: vertelt Netlify CMS dat het moet werken met je Git repo
backend:
  name: git-gateway
  branch: main # of master, afhankelijk van je default branch

# Media configuratie: waar worden geüploade afbeeldingen opgeslagen?
media_folder: "src/images/uploads" # Pad vanuit de root van de repo
public_folder: "/images/uploads" # Hoe de afbeeldingen worden benaderd op de site

# Definieer de content types (collecties) die je kunt beheren
collections:
  # Collectie 1: Blogs
  - name: "blog" # naam voor intern gebruik
    label: "Blogs" # Naam die je ziet in de CMS
    folder: "src/_content/blogs" # Waar worden de .md bestanden opgeslagen?
    create: true # Mogen gebruikers nieuwe blogs aanmaken?
    slug: "{{slug}}" # Hoe wordt de bestandsnaam gemaakt (bv. uit de titel)
    fields: # De velden die je kunt invullen voor een blogpost
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Korte samenvatting (excerpt)",
          name: "excerpt",
          widget: "text",
          required: false,
        }
      - { label: "Inhoud", name: "body", widget: "markdown" }

  # Collectie 2: Raadsleden
  - name: "raadsleden"
    label: "Raadsleden & Team"
    folder: "src/_content/raadsleden"
    create: true
    slug: "{{fields.naam | slugify}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" } 
      - { label: "Naam", name: "naam", widget: "string" }
      - {
          label: "Rol",
          name: "rol",
          widget: "string",
          hint: "bv. Fractievoorzitter, Raadslid, Bestuurslid"
        }
      - {
          label: "Volgorde op de lijst",
          name: "volgorde",
          widget: "number",
          value_type: "int",
          default: 99
        }
      - { label: "Foto", name: "foto", widget: "image" }
      - { label: "E-mail", name: "email", widget: "string", required: false }
      - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      - { label: "Biografie", name: "body", widget: "markdown" }


